In [2]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
from sklearn.pipeline import Pipeline

# feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler

In [7]:
from sklearn.linear_model import LogisticRegression

In [9]:
steps = [("Tranformer",StandardScaler()),("Classifier",LogisticRegression())]

In [10]:
steps

[('Tranformer', StandardScaler()), ('Classifier', LogisticRegression())]

In [38]:
Pipeline(steps)

Pipeline(steps=[('Scaling', StandardScaler()), ('PCA', PCA()), ('SVM', SVC())])

In [12]:
pipe = Pipeline(steps)

In [20]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000)

In [24]:
X.shape

(1000, 20)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [25]:
X_train

array([[ 1.27025643,  0.92679858,  0.14918453, ..., -0.31829372,
        -1.58616234, -0.56467723],
       [-1.05031486, -2.01018007,  0.67407081, ...,  0.02809804,
         1.70264574,  1.19574783],
       [ 1.63031067, -1.30056207,  0.45634619, ..., -0.64693989,
         0.40536091,  1.01012108],
       ...,
       [ 0.76923431,  0.61637456, -0.19924557, ..., -0.62122025,
         0.78850355,  0.28407456],
       [ 0.02684028, -1.27141691, -0.3851797 , ..., -1.25170719,
         0.35352388,  0.48077445],
       [ 0.99045371,  0.00691291,  0.71585729, ...,  0.95034573,
         0.91425474, -1.10461041]])

In [26]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('Tranformer', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [28]:
y_pred = pipe.predict(X_test)

In [30]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,

 # 2. Displaying a pipeline with standard scaler , dimensionality reduction and estimator

In [31]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [32]:
steps = [("Scaling",StandardScaler()) , ("PCA" , PCA()) , ("SVM" , SVC()) ]

In [34]:
pipe2 = Pipeline(steps)

In [35]:
pipe2.fit(X_train , y_train)

Pipeline(steps=[('Scaling', StandardScaler()), ('PCA', PCA()), ('SVM', SVC())])

In [37]:
pipe2.predict(X_test)

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

# 3. Coloumns transformer 

In [39]:
 from sklearn.impute import SimpleImputer

In [44]:
import numpy as np



In [52]:
numeric_processor = Pipeline(steps = [ ("imputation_mean" , SimpleImputer(missing_values = np.nan, strategy="mean")), ("scaler" , StandardScaler())])

In [53]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [55]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(steps = [ ("imputation_constant" , SimpleImputer(fill_value = "missing", strategy="constant")), 
                                          ("onehotencoder" ,  OneHotEncoder(handle_unknown="ignore"))])

In [56]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))])

combining processing techniques

In [58]:
from sklearn.compose import ColumnTransformer

In [63]:
preprocessor = ColumnTransformer(
   [("categorical" , categorical_processor,["gender","City"]) ,
   ("numerical" ,numeric_processor ,["age" ,"height"])]
)
    

In [64]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [65]:
#adding a estimator 

In [66]:
from sklearn.pipeline import make_pipeline

In [67]:
pipe = make_pipeline(preprocessor , LogisticRegression())

In [68]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])